### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by CLCK0622** [akhilmhdh/contributors-readme-action#63]
I would like to use it in my site, and I wonder if it can let me input the file path by myself?
e.g.: start/contributor.md

**Comment by CLCK0622** [comment]
oh the more serious problem is that when I use it in an org repo, it failed like this:
![image](https://github.com/akhilmhdh/contributors-readme-action/assets/36215258/1a528c20-d965-43c9-83b6-167e568066b2)
i suppose this may indicates that the github token is not valid
any solutions will help

**Comment by akhilmhdh** [comment]
Hey @CLCK0622 .

Yes u can change the file path. All you do is set the option `readme_path` while setting the action.

Ref: https://github.com/akhilmhdh/contributors-readme-action#optional-parameters

**Comment by akhilmhdh** [comment]
@CLCK0622 can u share me the repo url so that I can take a look at it. 

Now sure, have seen users configuring it for organization and was working great for them

**Comment by Prakash4844** [comment]
hey i am having same problem, i have already given readme_path here's repo can you take a look? https://github.com/Prakash4844/Get-Pair-Extraordinaire

**Comment by akhilmhdh** [comment]
Hey @Prakash4844 Thank you for taking your time. I really appreciate it. 

1. Weird i must say because the action uses node16. Ref: https://github.com/akhilmhdh/contributors-readme-action/blob/master/action.yml#L46 Need to check why its throwing an error like that. 

2. Ill definitely check you repo and resolve this. Release a patch. I got busy recently with some career changes happening. 

Ill raise the witch within a couple of days. v3 will be released next month which would be an amazing one.

**Comment by Prakash4844** [comment]
Thanks, eagerly waiting for new version. keep up the good work

**Comment by iChristwin** [comment]
I also had this issue today
https://github.com/iChristwin/M3ter-head/actions/runs/7340215377/job/19986281011

**Comment by akhilmhdh** [comment]
@Prakash4844 @iChristwin This is because you Github changed there action permission, You need to allow github action to read and write to repo. 

I have updated the readme usage workflow to enable this. 

Apologies for the very delayed response.
